export const DEFAULT_MODEL = "flux-dev";
export const DEFAULT_WIDTH = 1024;
export const DEFAULT_HEIGHT = 1024;
export const DEFAULT_STEPS = 25;
export const DEFAULT_CFG_SCALE = 2;
export const DEFAULT_SEED = null;
export const DEFAULT_HIDE_WATERMARK = true;
export const DEFAULT_RETURN_BINARY = true;

export const image_size = {
  square: { width: 1024, height: 1024 },
  portrait: { width: 768, height: 1024 },
  landscape: { width: 1024, height: 768 },
  wide: { width: 1536, height: 864 },
  huge: { width: 1536, height: 1536 },
};

export const stylePresets = [
  "3D Model",
  "Analog Film",
  "Anime",
  "Cinematic",
  "Comic Book",
  "Craft Clay",
  "Digital Art",
  "Enhance",
  "Fantasy Art",
  "Isometric Style",
  "Line Art",
  "Lowpoly",
  "Neon Punk",
  "Origami",
  "Photographic",
  "Pixel Art",
  "Texture",
  "Advertising",
  "Food Photography",
  "Real Estate",
  "Abstract",
  "Cubist",
  "Graffiti",
  "Hyperrealism",
  "Impressionist",
  "Pointillism",
  "Pop Art",
  "Psychedelic",
  "Renaissance",
  "Steampunk",
  "Surrealist",
  "Typography",
  "Watercolor",
  "Fighting Game",
  "GTA",
  "Super Mario",
  "Minecraft",
  "Pokemon",
  "Retro Arcade",
  "Retro Game",
  "RPG Fantasy Game",
  "Strategy Game",
  "Street Fighter",
  "Legend of Zelda",
  "Architectural",
  "Disco",
  "Dreamscape",
  "Dystopian",
  "Fairy Tale",
  "Gothic",
  "Grunge",
  "Horror",
  "Minimalist",
  "Monochrome",
  "Nautical",
  "Space",
  "Stained Glass",
  "Techwear Fashion",
  "Tribal",
  "Zentangle",
  "Collage",
  "Flat Papercut",
  "Kirigami",
  "Paper Mache",
  "Paper Quilling",
  "Papercut Collage",
  "Papercut Shadow Box",
  "Stacked Papercut",
  "Thick Layered Papercut",
  "Alien",
  "Film Noir",
  "HDR",
  "Long Exposure",
  "Neon Noir",
  "Silhouette",
  "Tilt-Shift"
]; 